apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CaptainLevi20/devops_kubernetes"
    path: "part4/4.7"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "exercises"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
