apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1-8
  template:
    metadata:
      labels:
        app: app-1-8
    spec:
      containers:
        - name: log-output
          image: captainlevi20/log-output:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
