apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- postgres-statefulset.yaml
- cronjob-random-todo.yaml
- todo-backend/k8s-backend.yaml
- todo-backend/configmap-backend.yaml
- todo-backend/secret-backend.yaml
